// Generated by `faust2tang --verilog-opcodes` from
// src/NanoTangFaust/compiler/IsaOpcodes.h -- do not edit by hand.
localparam [7:0] OP_NOP    = 8'h00;  // no operation
localparam [7:0] OP_PUSH   = 8'h01;  // push arg
localparam [7:0] OP_LOAD   = 8'h02;  // push heap[arg]
localparam [7:0] OP_STORE  = 8'h03;  // heap[arg] = pop
localparam [7:0] OP_LOADX  = 8'h04;  // i = pop; push heap[arg + i]
localparam [7:0] OP_STOREX = 8'h05;  // i = pop; v = pop; heap[arg + i] = v
localparam [7:0] OP_IN     = 8'h06;  // pop (frame index, ignored); push input[arg]
localparam [7:0] OP_OUT    = 8'h07;  // pop (frame index, ignored); output[arg] = pop
localparam [7:0] OP_DUP    = 8'h08;  // push T
localparam [7:0] OP_DROP   = 8'h09;  // pop
localparam [7:0] OP_SWAP   = 8'h0A;  // swap T and N
localparam [7:0] OP_OVER   = 8'h0B;  // push N
localparam [7:0] OP_TEE    = 8'h0C;  // heap[arg] = T (no pop)
localparam [7:0] OP_JMP    = 8'h10;  // pc = arg
localparam [7:0] OP_JZ     = 8'h11;  // if pop == 0: pc = arg
localparam [7:0] OP_JNZ    = 8'h12;  // if pop != 0: pc = arg
localparam [7:0] OP_CALL   = 8'h13;  // push return address; pc = arg
localparam [7:0] OP_RET    = 8'h14;  // pc = return address
localparam [7:0] OP_HALT   = 8'h15;  // end of this sample's computation
localparam [7:0] OP_ADD    = 8'h20;  // v1 + v2
localparam [7:0] OP_SUB    = 8'h21;  // v1 - v2
localparam [7:0] OP_MUL    = 8'h22;  // v1 * v2 (low 32 bits)
localparam [7:0] OP_DIV    = 8'h23;  // v1 / v2 (truncating; x/0 = 0)
localparam [7:0] OP_REM    = 8'h24;  // v1 % v2 (sign of v1; x%0 = 0)
localparam [7:0] OP_SHL    = 8'h25;  // v1 << (v2 & 31)
localparam [7:0] OP_ASR    = 8'h26;  // v1 >> (v2 & 31), arithmetic
localparam [7:0] OP_LSR    = 8'h27;  // v1 >> (v2 & 31), logical
localparam [7:0] OP_GT     = 8'h28;  // v1 > v2 (signed)
localparam [7:0] OP_LT     = 8'h29;  // v1 < v2
localparam [7:0] OP_GE     = 8'h2A;  // v1 >= v2
localparam [7:0] OP_LE     = 8'h2B;  // v1 <= v2
localparam [7:0] OP_EQ     = 8'h2C;  // v1 == v2
localparam [7:0] OP_NE     = 8'h2D;  // v1 != v2
localparam [7:0] OP_AND    = 8'h2E;  // v1 & v2
localparam [7:0] OP_OR     = 8'h2F;  // v1 | v2
localparam [7:0] OP_XOR    = 8'h30;  // v1 ^ v2
localparam [7:0] OP_MIN    = 8'h31;  // std::min(v1, v2), signed
localparam [7:0] OP_MAX    = 8'h32;  // std::max(v1, v2), signed
localparam [7:0] OP_ABS    = 8'h33;  // T = |T| (unary)
localparam [7:0] OP_FADD   = 8'h40;  // v1 + v2
localparam [7:0] OP_FSUB   = 8'h41;  // v1 - v2
localparam [7:0] OP_FMUL   = 8'h42;  // v1 * v2
localparam [7:0] OP_FDIV   = 8'h43;  // v1 / v2
localparam [7:0] OP_FGT    = 8'h44;  // v1 > v2
localparam [7:0] OP_FLT    = 8'h45;  // v1 < v2
localparam [7:0] OP_FGE    = 8'h46;  // v1 >= v2
localparam [7:0] OP_FLE    = 8'h47;  // v1 <= v2
localparam [7:0] OP_FEQ    = 8'h48;  // v1 == v2
localparam [7:0] OP_FNE    = 8'h49;  // v1 != v2
localparam [7:0] OP_FMIN   = 8'h4A;  // std::min(v1, v2)
localparam [7:0] OP_FMAX   = 8'h4B;  // std::max(v1, v2)
localparam [7:0] OP_FABS   = 8'h50;  // T = |T| (unary)
localparam [7:0] OP_FNEG   = 8'h51;  // T = -T (unary)
localparam [7:0] OP_I2F    = 8'h52;  // T = float(T) (unary)
localparam [7:0] OP_F2I    = 8'h53;  // T = int(T), truncating (unary)
localparam [7:0] OP_FSQRT  = 8'h54;  // T = sqrt(T) (unary)
localparam [7:0] OP_FFLOOR = 8'h55;  // T = floor(T) (unary)
