// Generated by `faust2tang --sketch` from synth.dsp -- do not edit.
// Faust interpreter bytecode of the program below, compiled on the
// microcontroller by FaustCompiler (TangNanoFaustCompiler.h).
//
//   // Monophonic subtractive synth: sawtooth -> ADSR -> resonant lowpass.
//   // freq/gain/gate follow Faust's MIDI naming, so TangNanoFaust's MIDI
//   // support plays it from note on/off messages.
//   declare name "synth";
//   import("stdfaust.lib");
//   
//   freq = hslider("freq", 220, 20, 2000, 0.01);
//   gain = hslider("gain", 0.5, 0, 1, 0.01);
//   gate = button("gate");
//   cutoff = hslider("cutoff [midi:ctrl 74]", 2000, 100, 8000, 1) : si.smoo;
//   res = hslider("resonance [midi:ctrl 71]", 2, 0.7, 10, 0.01) : si.smoo;
//   
//   process = os.sawtooth(freq) * en.adsr(0.01, 0.1, 0.8, 0.3, gate) * gain
//           : fi.resonlp(cutoff, res, 1);
#pragma once

static const char synth_fbc[] = R"FBC(interpreter_dsp_factory double
file_version 8
Faust version 2.70.3
compile_options -lang interp -ct 1 -es 1 -mcd 16 -mdd 1024 -mdy 33 -double -ftz 0 
name synth
sha_key 
opt_level 6
inputs 0 outputs 1
int_heap_size 14 real_heap_size 41 sr_offset 0 count_offset 3 iota_offset -1
meta_block
block_size 0
user_interface_block
block_size 9
opcode 280 kOpenVerticalBox offset -1 label "synth" key "" value "" init 0 min 0 max 0 step 0
opcode 292 kDeclare offset 3 label "" key "midi" value "ctrl 74" init 0 min 0 max 0 step 0
opcode 286 kAddHorizontalSlider offset 3 label "cutoff" key "" value "" init 2000 min 100 max 8000 step 1
opcode 286 kAddHorizontalSlider offset 19 label "freq" key "" value "" init 220 min 20 max 2000 step 0.01
opcode 286 kAddHorizontalSlider offset 23 label "gain" key "" value "" init 0.5 min 0 max 1 step 0.01
opcode 284 kAddButton offset 10 label "gate" key "" value "" init 0 min 0 max 0 step 0
opcode 292 kDeclare offset 7 label "" key "midi" value "ctrl 71" init 0 min 0 max 0 step 0
opcode 286 kAddHorizontalSlider offset 7 label "resonance" key "" value "" init 2 min 0.7 max 10 step 0.01
opcode 283 kCloseBox offset -1 label "" key "" value "" init 0 min 0 max 0 step 0
static_init_block
block_size 1
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
constants_block
block_size 50
opcode 3 kLoadInt int 0 real 0 offset1 0 offset2 0 name fSampleRate
opcode 26 kCastReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 192000 offset1 -1 offset2 -1
opcode 241 kMinf int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 0 kRealValue int 0 real 44.1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 1 offset2 0 name fConst1
opcode 2 kLoadReal int 0 real 0 offset1 1 offset2 0 name fConst1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 2 offset2 0 name fConst2
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 0 kRealValue int 0 real 3.141592653589793 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 6 offset2 0 name fConst3
opcode 0 kRealValue int 0 real 0.3 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 13 offset2 0 name fConst4
opcode 0 kRealValue int 0 real 0.01 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 16 offset2 0 name fConst5
opcode 2 kLoadReal int 0 real 0 offset1 16 offset2 0 name fConst5
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 17 offset2 0 name fConst6
opcode 0 kRealValue int 0 real 0.1 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 0.2 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 18 offset2 0 name fConst7
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 20 offset2 0 name fConst8
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
reset_ui
block_size 11
opcode 0 kRealValue int 0 real 2000 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 3 offset2 0 name fHslider0
opcode 0 kRealValue int 0 real 2 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 7 offset2 0 name fHslider1
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 10 offset2 0 name fButton0
opcode 0 kRealValue int 0 real 220 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 19 offset2 0 name fHslider2
opcode 0 kRealValue int 0 real 0.5 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 23 offset2 0 name fHslider3
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
clear_block
block_size 8
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 4 offset2 0 name l0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 4 offset2 0 name l0
opcode 12 kStoreIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 3 kLoadInt int 0 real 0 offset1 4 offset2 0 name l0
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 4 offset2 0 name l0
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 4 offset2 0 name l0
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 5 offset2 0 name l1
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 5 offset2 0 name l1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 3 kLoadInt int 0 real 0 offset1 5 offset2 0 name l1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 5 offset2 0 name l1
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 5 offset2 0 name l1
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 6 offset2 0 name l2
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 6 offset2 0 name l2
opcode 12 kStoreIndexedReal int 0 real 0 offset1 11 offset2 2 name fVec0
opcode 3 kLoadInt int 0 real 0 offset1 6 offset2 0 name l2
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 6 offset2 0 name l2
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 6 offset2 0 name l2
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 7 offset2 0 name l3
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 7 offset2 0 name l3
opcode 13 kStoreIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 3 kLoadInt int 0 real 0 offset1 7 offset2 0 name l3
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 7 offset2 0 name l3
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 7 offset2 0 name l3
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 8 offset2 0 name l4
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 8 offset2 0 name l4
opcode 12 kStoreIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 3 kLoadInt int 0 real 0 offset1 8 offset2 0 name l4
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 8 offset2 0 name l4
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 8 offset2 0 name l4
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 9 offset2 0 name l5
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 9 offset2 0 name l5
opcode 12 kStoreIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 3 kLoadInt int 0 real 0 offset1 9 offset2 0 name l5
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 9 offset2 0 name l5
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 9 offset2 0 name l5
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 10 offset2 0 name l6
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 12
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 10 offset2 0 name l6
opcode 12 kStoreIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 3 kLoadInt int 0 real 0 offset1 10 offset2 0 name l6
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 10 offset2 0 name l6
opcode 1 kInt32Value int 3 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 10 offset2 0 name l6
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
control_block
block_size 32
opcode 2 kLoadReal int 0 real 0 offset1 1 offset2 0 name fConst1
opcode 2 kLoadReal int 0 real 0 offset1 3 offset2 0 name fHslider0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 27 offset2 0 name fSlow0
opcode 2 kLoadReal int 0 real 0 offset1 1 offset2 0 name fConst1
opcode 2 kLoadReal int 0 real 0 offset1 7 offset2 0 name fHslider1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 28 offset2 0 name fSlow1
opcode 2 kLoadReal int 0 real 0 offset1 10 offset2 0 name fButton0
opcode 6 kStoreReal int 0 real 0 offset1 29 offset2 0 name fSlow2
opcode 2 kLoadReal int 0 real 0 offset1 29 offset2 0 name fSlow2
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 55 kEQReal int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 11 offset2 0 name iSlow3
opcode 2 kLoadReal int 0 real 0 offset1 19 offset2 0 name fHslider2
opcode 190 kAbsf int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 2.220446049250313e-16 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 30 offset2 0 name fSlow4
opcode 2 kLoadReal int 0 real 0 offset1 20 offset2 0 name fConst8
opcode 2 kLoadReal int 0 real 0 offset1 30 offset2 0 name fSlow4
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 31 offset2 0 name fSlow5
opcode 2 kLoadReal int 0 real 0 offset1 30 offset2 0 name fSlow4
opcode 2 kLoadReal int 0 real 0 offset1 0 offset2 0 name fConst0
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 32 offset2 0 name fSlow6
opcode 2 kLoadReal int 0 real 0 offset1 23 offset2 0 name fHslider3
opcode 6 kStoreReal int 0 real 0 offset1 33 offset2 0 name fSlow7
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
dsp_block
block_size 2
opcode 274 kLoop int 32 real 0 offset1 0 offset2 0
block_size 3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 12 offset2 0 name i0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 201
opcode 2 kLoadReal int 0 real 0 offset1 2 offset2 0 name fConst2
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 27 offset2 0 name fSlow0
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 2 kLoadReal int 0 real 0 offset1 6 offset2 0 name fConst3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 209 kTanf int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 34 offset2 0 name fTemp0
opcode 2 kLoadReal int 0 real 0 offset1 34 offset2 0 name fTemp0
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 35 offset2 0 name fTemp1
opcode 2 kLoadReal int 0 real 0 offset1 2 offset2 0 name fConst2
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 28 offset2 0 name fSlow1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 36 offset2 0 name fTemp2
opcode 2 kLoadReal int 0 real 0 offset1 34 offset2 0 name fTemp0
opcode 2 kLoadReal int 0 real 0 offset1 36 offset2 0 name fTemp2
opcode 2 kLoadReal int 0 real 0 offset1 35 offset2 0 name fTemp1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 37 offset2 0 name fTemp3
opcode 2 kLoadReal int 0 real 0 offset1 29 offset2 0 name fSlow2
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 11 offset2 2 name fVec0
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 11 kLoadIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 11 offset2 0 name iSlow3
opcode 37 kMultInt int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 13 kStoreIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 2 kLoadReal int 0 real 0 offset1 29 offset2 0 name fSlow2
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 11 offset2 2 name fVec0
opcode 53 kGEReal int 0 real 0 offset1 -1 offset2 -1
opcode 26 kCastReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 29 offset2 0 name fSlow2
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 0 kRealValue int 0 real -1 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 31 offset2 0 name fSlow5
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 38 offset2 0 name fTemp4
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 38 offset2 0 name fTemp4
opcode 52 kLTReal int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 13 offset2 0 name iTemp5
opcode 2 kLoadReal int 0 real 0 offset1 31 offset2 0 name fSlow5
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 39 offset2 0 name fTemp6
opcode 3 kLoadInt int 0 real 0 offset1 13 offset2 0 name iTemp5
opcode 277 kSelectReal int 0 real 0 offset1 0 offset2 0
block_size 2
opcode 2 kLoadReal int 0 real 0 offset1 39 offset2 0 name fTemp6
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 2
opcode 2 kLoadReal int 0 real 0 offset1 38 offset2 0 name fTemp4
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 3 kLoadInt int 0 real 0 offset1 13 offset2 0 name iTemp5
opcode 277 kSelectReal int 0 real 0 offset1 0 offset2 0
block_size 2
opcode 2 kLoadReal int 0 real 0 offset1 39 offset2 0 name fTemp6
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
block_size 9
opcode 2 kLoadReal int 0 real 0 offset1 32 offset2 0 name fSlow6
opcode 2 kLoadReal int 0 real 0 offset1 38 offset2 0 name fTemp4
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 31 offset2 0 name fSlow5
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 6 kStoreReal int 0 real 0 offset1 40 offset2 0 name fRec6
opcode 2 kLoadReal int 0 real 0 offset1 37 offset2 0 name fTemp3
opcode 2 kLoadReal int 0 real 0 offset1 34 offset2 0 name fTemp0
opcode 2 kLoadReal int 0 real 0 offset1 36 offset2 0 name fTemp2
opcode 2 kLoadReal int 0 real 0 offset1 35 offset2 0 name fTemp1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 2 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 34 offset2 0 name fTemp0
opcode 237 kPowf int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 2 offset1 -1 offset2 -1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 2 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 40 offset2 0 name fRec6
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real -1 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 13 offset2 0 name fConst4
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 11 kLoadIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 26 kCastReal int 0 real 0 offset1 -1 offset2 -1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 0.8 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 2 kLoadReal int 0 real 0 offset1 16 offset2 0 name fConst5
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 18 offset2 0 name fConst7
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 1 offset1 -1 offset2 -1
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 17 offset2 0 name fConst6
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 241 kMinf int 0 real 0 offset1 -1 offset2 -1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 0 kRealValue int 0 real 0 offset1 -1 offset2 -1
opcode 239 kMaxf int 0 real 0 offset1 -1 offset2 -1
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 2 kLoadReal int 0 real 0 offset1 33 offset2 0 name fSlow7
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 34 kSubReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 2 kLoadReal int 0 real 0 offset1 37 offset2 0 name fTemp3
opcode 0 kRealValue int 0 real 2 offset1 -1 offset2 -1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 36 kMultReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 32 kAddReal int 0 real 0 offset1 -1 offset2 -1
opcode 38 kDivReal int 0 real 0 offset1 -1 offset2 -1
opcode 3 kLoadInt int 0 real 0 offset1 12 offset2 0 name i0
opcode 25 kStoreOutput int 0 real 0 offset1 0 offset2 0
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 4 offset2 2 name fRec0
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 8 offset2 2 name fRec1
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 11 offset2 2 name fVec0
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 11 offset2 2 name fVec0
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 11 kLoadIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 13 kStoreIndexedInt int 0 real 0 offset1 1 offset2 2 name iRec3
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 14 offset2 2 name fRec4
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 21 offset2 2 name fRec5
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 1 kInt32Value int 2 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 1 kInt32Value int 0 real 0 offset1 -1 offset2 -1
opcode 10 kLoadIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 12 kStoreIndexedReal int 0 real 0 offset1 24 offset2 3 name fRec2
opcode 3 kLoadInt int 0 real 0 offset1 12 offset2 0 name i0
opcode 1 kInt32Value int 1 real 0 offset1 -1 offset2 -1
opcode 33 kAddInt int 0 real 0 offset1 -1 offset2 -1
opcode 7 kStoreInt int 0 real 0 offset1 12 offset2 0 name i0
opcode 3 kLoadInt int 0 real 0 offset1 3 offset2 0 name count
opcode 3 kLoadInt int 0 real 0 offset1 12 offset2 0 name i0
opcode 46 kLTInt int 0 real 0 offset1 -1 offset2 -1
opcode 279 kCondBranch int 0 real 0 offset1 0 offset2 0
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
opcode 275 kReturn int 0 real 0 offset1 -1 offset2 -1
)FBC";
