#pragma once
// Build artifacts written by the faust2tang command line tool:
// - prog.hex           program memory image (40-bit words), $readmemh format
// - desc.hex           parameter descriptor (text, one byte per line)
// - config.vh          Verilog defines (memory sizes, the boot program)
// - <name>_params.h    C++ parameter indices for sketches
// - <name>_program.h   the compiled program for TangNanoFaust::load()
// - report.txt         memory layout, parameters and cycle budget
// Plain string building (no file I/O), so it is usable anywhere.
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <string>
#include <vector>

#include "Compiler.h"

namespace nanotangfaust {
namespace compiler {
namespace output {

/// Address width for n entries (at least 1).
inline int aw(uint32_t n) {
  if (n < 2) n = 2;
  int w = 0;
  for (uint32_t v = n - 1; v; v >>= 1) w++;
  return w > 0 ? w : 1;
}

inline std::string fmt(const char *f, ...) __attribute__((format(printf, 1, 2)));
inline std::string fmt(const char *f, ...) {
  char buf[512];
  va_list ap;
  va_start(ap, f);
  vsnprintf(buf, sizeof(buf), f, ap);
  va_end(ap);
  return buf;
}

inline std::string num(double x) { return fmt("%.9g", x); }

inline std::string progHex(const std::vector<uint64_t> &words, uint32_t depth) {
  std::string s;
  for (uint64_t w : words) s += fmt("%010llx\n", (unsigned long long)w);
  for (uint32_t i = (uint32_t)words.size(); i < depth; i++) s += "0000000000\n";
  return s;
}

inline std::string descHex(const std::string &data, uint32_t depth) {
  std::string s;
  for (unsigned char b : data) s += fmt("%02x\n", b);
  for (uint32_t i = (uint32_t)data.size(); i < depth; i++) s += "00\n";
  return s;
}

/// Hardware the bitstream is built for; by default sized to the program.
struct Hardware {
  int progAw = 0, fastAw = 0, descAw = 0;
  int nIn = 0, nOut = 0;
  int useSdram = -1;  // -1: if the program needs it
  bool tdm = false;   // TDM output (NTF_TDM)
};

inline std::string configVh(const ProgramImage &c, const Hardware &hw) {
  int nIn = hw.nIn ? hw.nIn : (c.inputs > 1 ? c.inputs : 1);
  int nOut = hw.nOut ? hw.nOut : (c.outputs > 1 ? c.outputs : 1);
  bool sdram = hw.useSdram < 0 ? c.sdramWords != 0 : hw.useSdram != 0;
  std::string s = "// Generated by faust2tang for '" + c.name + "' -- do not edit.\n";
  s += fmt("`define NTF_PROG_AW     %d\n", hw.progAw);
  s += fmt("`define NTF_FAST_AW     %d\n", hw.fastAw);
  s += fmt("`define NTF_FAST_WORDS  %d\n", 1 << hw.fastAw);
  s += fmt("`define NTF_DESC_AW     %d\n", hw.descAw);
  s += fmt("`define NTF_DESC_LEN    %d\n", (int)c.descriptor.size());
  s += fmt("`define NTF_N_IN        %d\n", nIn);
  s += fmt("`define NTF_N_OUT       %d\n", nOut);
  s += fmt("`define NTF_DSP_INPUTS  %d\n", c.inputs);
  s += fmt("`define NTF_DSP_OUTPUTS %d\n", c.outputs);
  s += fmt("`define NTF_N_PARAMS    %d\n", (int)c.params.size());
  s += fmt("`define NTF_DSP_ENTRY   %u\n", c.dspEntry);
  s += fmt("`define NTF_BOOT_ENTRY  %u\n", c.bootEntry);
  s += fmt("`define NTF_SAMPLE_RATE %u\n", c.sampleRate);
  s += fmt("`define NTF_USE_SDRAM   %d\n", sdram ? 1 : 0);
  if (hw.tdm) s += "`define NTF_TDM\n";
  return s;
}

/// Identifier from a name: non-alphanumerics -> '_', upper case.
inline std::string ident(const std::string &name) {
  std::string s;
  bool sep = false;
  for (char ch : name) {
    bool alnum = (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9');
    if (alnum) {
      if (sep && !s.empty()) s += '_';
      sep = false;
      s += (ch >= 'a' && ch <= 'z') ? (char)(ch - 32) : ch;
    } else {
      sep = true;
    }
  }
  if (s.empty() || (s[0] >= '0' && s[0] <= '9')) s = "P_" + s;
  return s;
}

inline std::string lower(std::string s) {
  for (char &ch : s)
    if (ch >= 'A' && ch <= 'Z') ch += 32;
  return s;
}

inline std::string paramsHeader(const ProgramImage &c) {
  std::string ns = lower(ident(c.name));
  std::string s = "// Generated by faust2tang for '" + c.name + "' -- do not edit.\n";
  s += "// Parameter indices for TangNanoFaust::setParameter(). The FPGA also\n";
  s += "// describes these at runtime, so this header is optional.\n";
  s += "#pragma once\n";
  s += "#define NTF_" + ident(c.name) + "_PARAMS_H\n\n";
  s += "namespace " + ns + " {\n";
  s += fmt("constexpr int kInputs = %d;\n", c.inputs);
  s += fmt("constexpr int kOutputs = %d;\n", c.outputs);
  s += fmt("constexpr int kSampleRate = %u;\n", c.sampleRate);
  s += fmt("constexpr int kParameterCount = %d;\n", (int)c.params.size());
  std::vector<std::string> used;
  for (const Param &p : c.params) {
    std::string id = lower(ident(p.path)), name = "k";
    bool up = true;
    for (char ch : id) {
      if (ch == '_') {
        up = true;
        continue;
      }
      name += (up && ch >= 'a' && ch <= 'z') ? (char)(ch - 32) : ch;
      up = false;
    }
    bool dup = true;
    while (dup) {
      dup = false;
      for (auto &u : used)
        if (u == name) dup = true;
      if (dup) name += "_";
    }
    used.push_back(name);
    s += "constexpr int " + name + " = " + std::to_string(p.index) + ";  // " + p.kind + " " +
         p.path + " [" + num(p.min) + ", " + num(p.max) + "] init " + num(p.init) + "\n";
  }
  s += "}\n";
  return s;
}

/// The program as one binary block (src/NanoTangFaust/ProgramBlob.h), for
/// sending over a network; parseProgramBlob() reads it back.
inline std::string programBlob(const ProgramImage &c) {
  std::string s;
  auto put = [&](uint32_t v, int n) {
    for (int i = 0; i < n; i++) s += (char)((v >> (8 * i)) & 0xFF);
  };
  std::string name = c.name.substr(0, 255);
  s += "NTFP";
  put(1, 1);  // format version
  put(c.minProtocol, 1);
  put((uint32_t)c.inputs, 1);
  put((uint32_t)c.outputs, 1);
  put((uint32_t)c.params.size(), 1);
  put((uint32_t)name.size(), 1);
  put((uint32_t)c.descriptor.size(), 2);
  put((uint32_t)c.program.size(), 4);
  put(c.dspEntry, 2);
  put(c.bootEntry, 2);
  put(c.sampleRate, 4);
  put(c.fastWords, 4);
  put(c.sdramWords, 4);
  s += name;
  s += '\0';
  s += c.descriptor;
  s += '\0';
  for (uint64_t w : c.program)
    for (int b = 0; b < 5; b++) s += (char)((w >> (8 * b)) & 0xFF);
  return s;
}

inline std::string programHeader(const ProgramImage &c) {
  std::string ns = lower(ident(c.name));
  std::string s = "// Generated by faust2tang for '" + c.name + "' -- do not edit.\n";
  s += "// Load with TangNanoFaust::load(" + ns + "::program) -- no FPGA rebuild needed.\n";
  s += "#pragma once\n#include <NanoTangFaust.h>\n\n";
  s += "namespace " + ns + " {\n";
  s += "static const uint8_t kCode[] = {\n";
  for (uint64_t w : c.program) {
    s += "    ";
    for (int b = 0; b < 5; b++) s += fmt(b ? ", 0x%02x" : "0x%02x", (unsigned)((w >> (8 * b)) & 0xFF));
    s += ",\n";
  }
  s += "};\n";
  std::string esc;
  for (char ch : c.descriptor) {
    if (ch == '\\') esc += "\\\\";
    else if (ch == '"') esc += "\\\"";
    else if (ch == '\n') esc += "\\n\"\n    \"";
    else esc += ch;
  }
  s += "static const char kDescriptor[] =\n    \"" + esc + "\";\n\n";
  s += "static const nanotangfaust::ProgramData program = [] {\n";
  s += "  nanotangfaust::ProgramData p;\n";
  s += "  p.name = \"" + c.name + "\";\n";
  s += "  p.code = kCode;\n";
  s += fmt("  p.words = %d;\n", (int)c.program.size());
  s += "  p.descriptor = kDescriptor;\n";
  s += fmt("  p.descriptorLength = %d;\n", (int)c.descriptor.size());
  s += fmt("  p.dspEntry = %u;\n", c.dspEntry);
  s += fmt("  p.bootEntry = %u;\n", c.bootEntry);
  s += fmt("  p.inputs = %d;\n", c.inputs);
  s += fmt("  p.outputs = %d;\n", c.outputs);
  s += fmt("  p.parameters = %d;\n", (int)c.params.size());
  s += fmt("  p.sampleRate = %u;\n", c.sampleRate);
  s += fmt("  p.fastWords = %u;\n", c.fastWords);
  s += fmt("  p.sdramWords = %u;\n", c.sdramWords);
  s += fmt("  p.minProtocol = %d;\n", c.minProtocol);
  s += "  return p;\n}();\n}\n";
  return s;
}

inline std::string pad(const std::string &s, size_t w) {
  return s.size() >= w ? s : s + std::string(w - s.size(), ' ');
}

/// `cyclesControl`: a sample right after a parameter change (control block
/// + dsp block); `cyclesMax`: worst other sample (dsp block only).
inline std::string report(const ProgramImage &c, const std::vector<Compiler::Region> &layout,
                          long cyclesBoot, long cyclesControl, long cyclesMax, uint32_t clkHz) {
  uint32_t budget = clkHz / c.sampleRate;
  std::string routines;
  for (size_t i = 0; i < c.routines.size(); i++) routines += (i ? ", " : "") + c.routines[i];
  if (routines.empty()) routines = "-";
  std::string s;
  s += fmt("DSP '%s': %d in, %d out, %u Hz\n", c.name.c_str(), c.inputs, c.outputs, c.sampleRate);
  s += fmt("program: %d words; math routines: %s\n", (int)c.program.size(), routines.c_str());
  s += fmt("block RAM: %u words; SDRAM: %u words\n", c.fastWords, c.sdramWords);
  s += fmt("cycles per sample: %ld of %u available at %g MHz (%.0f%%)\n", cyclesMax, budget,
           clkHz / 1e6, 100.0 * cyclesMax / budget);
  s += fmt("after a parameter change: %ld cycles (%.0f%%)\n", cyclesControl,
           100.0 * cyclesControl / budget);
  s += fmt("boot: %ld cycles (%.1f ms)\n\n", cyclesBoot, (double)cyclesBoot / clkHz * 1000);
  s += "memory layout:\n";
  for (const auto &r : layout)
    s += fmt("  %s fbc offset %6d size %7d -> %s 0x%06x\n", pad(r.what, 12).c_str(), r.offset,
             r.size, r.addr >= kSdramBase ? "SDRAM" : "BRAM", r.addr);
  s += "\nparameters:\n";
  for (const Param &p : c.params) {
    std::string meta;
    for (size_t i = 0; i < p.meta.size(); i++)
      meta += (i ? " [" : "[") + p.meta[i].first + ":" + p.meta[i].second + "]";
    s += fmt("  %2d %s %s init %s range [%s, %s] addr 0x%04x %s\n", p.index,
             pad(p.kind, 9).c_str(), pad(p.path, 30).c_str(), num(p.init).c_str(),
             num(p.min).c_str(), num(p.max).c_str(), p.addr, meta.c_str());
  }
  return s;
}

/// FBC text without its meta_block (library credits: the compiler doesn't
/// need them, and they take flash on a microcontroller).
inline std::string stripMeta(const std::string &fbc) {
  std::string out;
  size_t p = 0;
  int skip = -1;  // lines still to drop
  while (p < fbc.size()) {
    size_t e = fbc.find('\n', p);
    if (e == std::string::npos) e = fbc.size();
    std::string line = fbc.substr(p, e - p);
    p = e + 1;
    if (line == "meta_block") {
      skip = -2;  // next line is block_size N
      out += "meta_block\nblock_size 0\n";
      continue;
    }
    if (skip == -2) {
      skip = atoi(line.c_str() + 11);
      continue;
    }
    if (skip > 0) {
      skip--;
      continue;
    }
    out += line + "\n";
  }
  return out;
}

/// C++ header with a program's FBC text (and its Faust source as a
/// comment), for compiling on the microcontroller with FaustCompiler.
inline std::string fbcHeader(const std::string &name, const std::string &fbc,
                             const std::string &dspSource) {
  std::string id = lower(ident(name));
  std::string s = "// Generated by `faust2tang --sketch` from " + name + ".dsp -- do not edit.\n";
  s += "// Faust interpreter bytecode of the program below, compiled on the\n";
  s += "// microcontroller by FaustCompiler (NanoTangFaustCompiler.h).\n//\n";
  size_t p = 0;
  while (p < dspSource.size()) {
    size_t e = dspSource.find('\n', p);
    if (e == std::string::npos) e = dspSource.size();
    s += "//   " + dspSource.substr(p, e - p) + "\n";
    p = e + 1;
  }
  s += "#pragma once\n\n";
  s += "static const char " + id + "_fbc[] = R\"FBC(" + stripMeta(fbc) + ")FBC\";\n";
  return s;
}

/// gateware/rtl/isa_opcodes.vh from IsaOpcodes.h.
inline std::string verilogOpcodes() {
  std::string s = "// Generated by `faust2tang --verilog-opcodes` from\n"
                  "// src/NanoTangFaust/compiler/IsaOpcodes.h -- do not edit by hand.\n";
  for (int i = 0; i < kCoreOpCount; i++)
    s += fmt("localparam [7:0] OP_%s = 8'h%02X;  // %s\n", pad(kCoreOps[i].name, 6).c_str(),
             kCoreOps[i].code, kCoreOps[i].description);
  return s;
}

}  // namespace output
}  // namespace compiler
}  // namespace nanotangfaust
